# general settings
#name: BHAN_x4_C48B4R2_L1_soft_DF_head
name: BHAN_x4_xr_1e4
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
gpu_ids: 4
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
#    dataroot_gt: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
#    (for lmdb)
    dataroot_gt: ../datasets/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: ../datasets/DF2K/LR_train/DF2K_train_LR_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb
      # (for lmdb)
      # type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

#  val:
#    name: BSD100
#    type: PairedImageDataset
#    dataroot_gt: ../datasets/B100/HR
#    dataroot_lq: ../datasets/B100/LR_bicubic/X4
#    io_backend:
#      type: disk
  val:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: ../datasets/DF2K/DIV2K_valid_HR
    dataroot_lq: ../datasets/DF2K/DIV2K_valid_LR/X4
    io_backend:
      type: disk

# network structures
network_g:
  type: BHAN
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: 4
  heads: [2,2,4,8]
  ffn_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  upscale: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: 0.00001


  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
